### ISSUE TITLE
Hello from Earth2Studio

### ISSUE THREAD

**Issue by NickGeneva** [secondlaw-ai/skyrim#12]
Hi there,

I noticed your currently working with some Nvidia packages to get access to some models. That's great to see!
Recently we have been working on build up a more production level package focused on components to help enable downstream applications just like this.

https://github.com/NVIDIA/earth2studio

The key difference between this package and earth2mip is that:
- earth2studio focus on providing Python components for allow people to build their own inference workflows / applications
- earth2mip provides predefined intercomparison functions

We plan on slowly integrating earth2studio with other packages in the future. You may be interested in:

https://nvidia.github.io/earth2studio/modules/models.html

(Noticed you're looking at FuXi, wanted to also mention we are in the middle of integrating this ourselves into earth2studio. May be able to avoid redundant work there :) )

Cheers.

**Comment by m13uz** [comment]
Hello @NickGeneva,

Thank you for bringing the earth2studio repository to our attention — it seems incredibly useful!

Could you share more details about your development roadmap? I'm also curious to know if earth2mip will continue to be maintained.

Thanks again!
