### ISSUE TITLE
MetNet-3 Implementation

### ISSUE THREAD

**Issue by dmvinson** [secondlaw-ai/skyrim#14]
Hey, I'm interested in implementing MetNet-3 for use at work. I see that it's planned as a model to implement after FuXi. Do you have any initial approach that is being considered? I don't see MetNet-3 implemented in ai-models or earth2mip, but if there's another library you are planning on using, I'd be happy to implement it within this repo.

**Comment by m13uz** [comment]
Hey, @dmvinson! We have been thinking of creating a separate repo for the training (a nano version of it) and using Skyrim to serve the predictions. We are currently trying to figure out the required compute. We would be happy to collaborate!
